insert into provincia (codigo, descripcion) values('X', 'CORDOBA');
insert into provincia (codigo, descripcion) values('T', 'TUCUMAN');
insert into provincia (codigo, descripcion) values('Y', 'JUJUY');
insert into provincia (codigo, descripcion) values('M', 'MENDOZA'); 
insert into provincia (codigo, descripcion) values('H', 'CHACO');
insert into provincia (codigo, descripcion) values('Z', 'SANTA CRUZ');                 
insert into provincia (codigo, descripcion) values('A', 'SALTA');
insert into provincia (codigo, descripcion) values('K', 'CATAMARCA');
insert into provincia (codigo, descripcion) values('D', 'SAN LUIS');
insert into provincia (codigo, descripcion) values('R', 'RIO NEGRO');
insert into provincia (codigo, descripcion) values('V', 'TIERRA DEL FUEGO');
insert into provincia (codigo, descripcion) values('G', 'SANTIAGO DEL ESTERO');
insert into provincia (codigo, descripcion) values('B', 'BUENOS AIRES');
insert into provincia (codigo, descripcion) values('P', 'FORMOSA');
insert into provincia (codigo, descripcion) values('W', 'CORRIENTES');
insert into provincia (codigo, descripcion) values('C', 'CAPITAL FEDERAL');
insert into provincia (codigo, descripcion) values('E', 'ENTRE RIOS');
insert into provincia (codigo, descripcion) values('N', 'MISIONES');
insert into provincia (codigo, descripcion) values('F', 'LA RIOJA');
insert into provincia (codigo, descripcion) values('L', 'LA PAMPA');
insert into provincia (codigo, descripcion) values('J', 'SAN JUAN');
insert into provincia (codigo, descripcion) values('Q', 'NEUQUEN');
insert into provincia (codigo, descripcion) values('I', 'INDEFINIDA');
insert into provincia (codigo, descripcion) values('S', 'SANTA FE');
